### ISSUE TITLE
Frontend Bug in the demo example

### ISSUE THREAD

**Issue by josuegarza42** [Ladvace/Grid-astro-portfolio#1]
Hi:), Hey I was modifying your repository and I found a bug.

In your page https://gianmarco.xyz/ is not the bug.

but in https://sparkly-speculoos-0c9197.netlify.app/ (the demo example that is in your repository).

It turns out that if I run the web page on certain devices it looks like this:

![image](https://github.com/Ladvace/astro-bento-portfolio/assets/44554474/798f6a9a-a4c8-4765-a064-b959fb792900)

This is only happening to me on apple devices, which I find very curious haha

**Comment by Ladvace** [comment]
could you tell me what device did you try?

**Comment by josuegarza42** [comment]
It was on an iphone 13 and iphone XR (demo example)

**Comment by Ladvace** [comment]
@josuegarza42 I should have fixed it, let me know if you still encounter this problem, otherwise, I'm gonna close the issue

**Comment by josuegarza42** [comment]
Ok, let me test it:)

**Comment by josuegarza42** [comment]
Indeed, the 2 problems were solved, thank you very much for everything:)
