### ISSUE TITLE
Waiting for custodian.pw

### ISSUE THREAD

**Issue by taynotfound** [Ladvace/Grid-astro-portfolio#22]
Hey i keep having this issue. I cant find it anywhere in the Code. Any clue how i can fix this? It makes my website load infinitely.
![image](https://github.com/Ladvace/astro-bento-portfolio/assets/50525948/bbe86b81-68a8-4805-b139-cfd34ea8e3a5)

It doesnt have his issue locally

**Comment by Ladvace** [comment]
I need to be honest, not sure what it is, what OS and browser do you use?

**Comment by taynotfound** [comment]
I use Fedora Linux and Firefox

**Comment by taynotfound** [comment]
But yeah i didnt find it too so its quite wierd
