### ISSUE TITLE
EMFile Too many files open

### ISSUE THREAD

**Issue by granth23** [Ladvace/Grid-astro-portfolio#6]
I am getting a certain error stating 
Error: EMFILE: too many open files, open 'C:\Users\Granth Bagadia\Code\Projects\Websites\Portfolio\node_modules\astro\dist\assets\utils\vendor\image-size\types\heif.d.ts'
Probably something with my own device but not really sure on how to solve this.

Thank You

**Comment by Ladvace** [comment]
when did you get this error, trying to run it in dev with `pnpm dev`?

**Comment by granth23** [comment]
No I was doing 
`npm run dev`

**Comment by Ladvace** [comment]
try using `pnpm` instead if you can

**Comment by granth23** [comment]
No i dont have pnpm installed

**Comment by Ladvace** [comment]
what version of node/npm do you use?

**Comment by granth23** [comment]
Node: v20.11.1
npm@9.7.1

**Comment by granth23** [comment]
I did install `pnpm` its working now, thanks

**Comment by granth23** [comment]
Done

**Comment by Ladvace** [comment]
I tried with npm and it works with that too, In case anyone else get this problem I'll try to dig into it, for now I suggest using pnpm
